#![cfg_attr(
    not(test),
    expect(dead_code, reason = "pure patch encoder awaits a later caller")
)]

use sha2::{Digest, Sha256};

#[path = "rewriter_patch/shards.rs"]
pub(super) mod shards;

const PATCH_HEADER_START: &str = "From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001\nFrom: Mesh-LLM CI <ci@mesh-llm.local>\nDate: Thu, 1 Jan 1970 00:00:00 +0000\nSubject: [PATCH] ";
const PATCH_HEADER_END: &str = "\n\nGenerated by tools/skippy-stage-rewriter from compiler-proven builder\nshapes. Auxiliary sidecars and whole-model multi-domain graphs are proven\nseparately and remain outside the primary decoder stage interval.\n\n---\n";
const PATCH_TRAILER: &str = "-- \n2.54.0\n\n";

pub(super) struct MailPatch {
    pub(super) bytes: Vec<u8>,
    pub(super) diff_sha256: String,
}

#[derive(Debug, PartialEq, Eq)]
pub(super) enum PatchError {
    EmptyDiff,
    InvalidUtf8,
}

impl std::fmt::Display for PatchError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::EmptyDiff => formatter.write_str("generation produced an empty model patch"),
            Self::InvalidUtf8 => formatter.write_str("generated model diff is not UTF-8"),
        }
    }
}

impl std::error::Error for PatchError {}

pub(super) fn encode_mail_patch(subject: &str, diff: &[u8]) -> Result<MailPatch, PatchError> {
    if diff.is_empty() {
        return Err(PatchError::EmptyDiff);
    }
    std::str::from_utf8(diff).map_err(|_| PatchError::InvalidUtf8)?;

    let mut bytes = Vec::with_capacity(
        PATCH_HEADER_START.len()
            + subject.len()
            + PATCH_HEADER_END.len()
            + diff.len()
            + PATCH_TRAILER.len(),
    );
    bytes.extend_from_slice(PATCH_HEADER_START.as_bytes());
    bytes.extend_from_slice(subject.as_bytes());
    bytes.extend_from_slice(PATCH_HEADER_END.as_bytes());
    bytes.extend_from_slice(diff);
    bytes.extend_from_slice(PATCH_TRAILER.as_bytes());

    Ok(MailPatch {
        bytes,
        diff_sha256: hex::encode(Sha256::digest(diff)),
    })
}

#[cfg(test)]
mod tests {
    use super::{PatchError, encode_mail_patch};

    const SUBJECT: &str = "skippy: generate model-family stage controls";
    const ORDERED_DIFF: &[u8] =
        include_bytes!("../../tests/fixtures/migration/rewriter-patch/two-model.diff");
    const ORDERED_PATCH: &[u8] =
        include_bytes!("../../tests/fixtures/migration/rewriter-patch/two-model.patch");

    #[test]
    fn exact_mail_bytes_and_raw_diff_digest_when_two_models_are_ordered() {
        // Given: the frozen legacy two-model diff and complete mail patch.
        // When: the pure encoder receives the original diff bytes.
        let result = encode_mail_patch(SUBJECT, ORDERED_DIFF).unwrap();

        // Then: the complete output and input-derived digest match independent fixtures.
        assert_eq!(result.bytes, ORDERED_PATCH);
        assert_eq!(
            result.diff_sha256,
            "c1bf5a727845c2ab193c43dc8884812906fcc5f4b30a9a8e55a4358ff6a5c9ce"
        );
    }

    #[test]
    fn utf8_and_crlf_bytes_remain_unchanged_when_encoding_mail_patch() {
        // Given: a Unicode text change whose hunk contains CRLF.
        let diff = b"diff --git a/src/models/cafe.cpp b/src/models/cafe.cpp\n--- a/src/models/cafe.cpp\n+++ b/src/models/cafe.cpp\n@@ -1 +1 @@\n-caf\xc3\xa9\r\n+caf\xc3\xa8\r\n";
        let expected = b"From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001\nFrom: Mesh-LLM CI <ci@mesh-llm.local>\nDate: Thu, 1 Jan 1970 00:00:00 +0000\nSubject: [PATCH] skippy: generate model-family stage controls\n\nGenerated by tools/skippy-stage-rewriter from compiler-proven builder\nshapes. Auxiliary sidecars and whole-model multi-domain graphs are proven\nseparately and remain outside the primary decoder stage interval.\n\n---\ndiff --git a/src/models/cafe.cpp b/src/models/cafe.cpp\n--- a/src/models/cafe.cpp\n+++ b/src/models/cafe.cpp\n@@ -1 +1 @@\n-caf\xc3\xa9\r\n+caf\xc3\xa8\r\n-- \n2.54.0\n\n";
        // When: the exact captured bytes are encoded.
        let result = encode_mail_patch(SUBJECT, diff).unwrap();

        // Then: the encoded mail contains the unchanged hunk and hashes the raw diff.
        assert_eq!(result.bytes, expected);
        assert_eq!(
            result.diff_sha256,
            "5e71a74782aab731bcd6afd25dab0249829c17695539bf268c442ac525d4f1bc"
        );
    }

    #[test]
    fn digest_changes_when_one_hunk_byte_changes() {
        // Given: one byte changes in a known, complete diff.
        let changed = b"diff --git a/src/models/cafe.cpp b/src/models/cafe.cpp\n--- a/src/models/cafe.cpp\n+++ b/src/models/cafe.cpp\n@@ -1 +1 @@\n-caf\xc3\xa9\r\n+caf\xc3\xa9\r\n";
        // When: the changed diff is encoded.
        let result = encode_mail_patch(SUBJECT, changed).unwrap();

        // Then: the digest matches the changed input, not the earlier patch bytes.
        assert_eq!(
            result.diff_sha256,
            "220c3cc5e136e4a27fc45ec0f14f71d9780460c20831ada226f01faa9836431f"
        );
    }

    #[test]
    fn caller_subject_is_preserved_when_it_differs_from_the_generator_default() {
        let subject = "skippy: annotate {fixture} caf\u{e9} graph semantics";
        let expected = std::str::from_utf8(ORDERED_PATCH)
            .unwrap()
            .replacen(SUBJECT, subject, 1);

        let result = encode_mail_patch(subject, ORDERED_DIFF).unwrap();

        assert_eq!(result.bytes, expected.as_bytes());
        assert_eq!(
            result.diff_sha256,
            "c1bf5a727845c2ab193c43dc8884812906fcc5f4b30a9a8e55a4358ff6a5c9ce"
        );
    }

    #[test]
    fn empty_diff_is_rejected_before_encoding() {
        assert!(matches!(
            encode_mail_patch(SUBJECT, b""),
            Err(PatchError::EmptyDiff)
        ));
    }

    #[test]
    fn malformed_utf8_is_rejected_before_encoding() {
        assert!(matches!(
            encode_mail_patch(SUBJECT, b"\xff"),
            Err(PatchError::InvalidUtf8)
        ));
    }
}
