self-hosted-runner:
  labels:
    - self-hosted
    - Linux
    - X64
    - ARM64
    - amd64
    - gpu-nvidia
    - mesh-llm-amd64
    - mesh-llm-arm64
    - depot-ubuntu-24.04
    - depot-ubuntu-24.04-4
    - depot-ubuntu-24.04-8
    - depot-ubuntu-24.04-16
