[package]
name = "skippy-api"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Shared Skippy model preparation and serving lifecycle API"
repository = "https://github.com/Mesh-LLM/mesh-llm"
readme = "README.md"

[features]
default = []
dynamic-native-runtime = ["skippy-runtime/dynamic-native-runtime"]

[dependencies]
anyhow.workspace = true
hex = "0.4"
sha2.workspace = true
model-artifact = { path = "../model-artifact", version = "0.76.1" }
skippy-protocol = { path = "../skippy-protocol", version = "0.76.1" }
skippy-runtime = { path = "../skippy-runtime", version = "0.76.1" }
serde.workspace = true
serde_json.workspace = true
tracing = "0.1"
skippy-package-format = { path = "../skippy-package-format", version = "0.76.1" }
skippy-model = { path = "../skippy-model", version = "0.76.1" }
skippy-ffi = { path = "../skippy-ffi", version = "0.76.1", default-features = false }

model-ref = { path = "../model-ref", version = "0.76.1" }
model-hf = { path = "../model-hf", version = "0.76.1" }
hf_hub = { package = "skippy-hf-hub", path = "../skippy-hf-hub", version = "0.76.1", default-features = false, features = ["blocking"] }
same-file = "1.0.6"

[dev-dependencies]
tempfile = "3"
