use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

#[derive(Deserialize, Serialize)]
pub(super) struct Row {
    pub label: String,
    #[serde(rename = "ref")]
    pub reference: String,
    pub commit: String,
    pub concurrency: u32,
    pub passes: u64,
    pub trajectories_per_pass: u64,
    pub trajectory_replays: u64,
    pub requests: u64,
    pub successful_requests: u64,
    pub failed_requests: u64,
    pub failed_request_ids: Vec<String>,
    pub failure_identity_known: bool,
    pub content_identity: BTreeMap<String, Vec<String>>,
    pub content_identity_known: bool,
    pub content_stable_across_passes: bool,
    pub prompt_tokens_min: Option<u64>,
    pub prompt_tokens_max: Option<u64>,
    pub success_pct: Option<f64>,
    pub budget_exhausted_pct: Option<f64>,
    pub agent_steps_per_second: Option<f64>,
    pub agent_steps_per_second_min: Option<f64>,
    pub agent_steps_per_second_max: Option<f64>,
    pub workload_output_tokens_per_second: Option<f64>,
    pub workload_output_tokens_per_second_min: Option<f64>,
    pub workload_output_tokens_per_second_max: Option<f64>,
    pub decode_tokens_per_second: Option<f64>,
    pub decode_tokens_per_second_min: Option<f64>,
    pub decode_tokens_per_second_max: Option<f64>,
    pub ttft_p50_seconds: Option<f64>,
    pub ttft_p50_seconds_min: Option<f64>,
    pub ttft_p50_seconds_max: Option<f64>,
    pub ttft_p95_seconds: Option<f64>,
    pub mean_in_flight: Option<f64>,
    pub concurrency_utilization_pct: Option<f64>,
    pub cache_pct: Option<f64>,
    pub delta_comparable: bool,
    pub agent_steps_per_second_delta_pct: Option<f64>,
    pub workload_output_tokens_per_second_delta_pct: Option<f64>,
    pub decode_tokens_per_second_delta_pct: Option<f64>,
    pub ttft_p50_seconds_delta_pct: Option<f64>,
}

pub(super) const COLUMNS: &[&str] = &[
    "label",
    "ref",
    "commit",
    "concurrency",
    "passes",
    "trajectories_per_pass",
    "trajectory_replays",
    "requests",
    "successful_requests",
    "failed_requests",
    "failed_request_ids",
    "failure_identity_known",
    "content_identity",
    "content_identity_known",
    "content_stable_across_passes",
    "prompt_tokens_min",
    "prompt_tokens_max",
    "success_pct",
    "budget_exhausted_pct",
    "agent_steps_per_second",
    "agent_steps_per_second_min",
    "agent_steps_per_second_max",
    "workload_output_tokens_per_second",
    "workload_output_tokens_per_second_min",
    "workload_output_tokens_per_second_max",
    "decode_tokens_per_second",
    "decode_tokens_per_second_min",
    "decode_tokens_per_second_max",
    "ttft_p50_seconds",
    "ttft_p50_seconds_min",
    "ttft_p50_seconds_max",
    "ttft_p95_seconds",
    "mean_in_flight",
    "concurrency_utilization_pct",
    "cache_pct",
    "delta_comparable",
    "agent_steps_per_second_delta_pct",
    "workload_output_tokens_per_second_delta_pct",
    "decode_tokens_per_second_delta_pct",
    "ttft_p50_seconds_delta_pct",
];
