[package]
name = "mesh-llm-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["client", "serve"]
client = ["dep:anyhow", "native-runtime", "dep:serde_json"]
serve = ["dep:anyhow", "native-runtime", "dep:serde_json"]
console = ["dep:mesh-llm-console-server"]
web-ui = ["console", "mesh-llm-host-runtime?/web-ui"]
native-runtime = ["dep:mesh-llm-host-runtime"]
dynamic-native-runtime = ["native-runtime", "mesh-llm-host-runtime/dynamic-native-runtime"]

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
mesh-llm-console-server = { path = "../mesh-llm-console-server", optional = true }
mesh-llm-host-runtime = { path = "../mesh-llm-host-runtime", default-features = false, optional = true }
