//! Catalog of operator controls and their owning runtime fields.

#[derive(Clone, Copy, Debug)]
pub enum Kind {
    Bool,
    Text,
    Content,
    Json,
    Unsigned,
    Integer,
    Number,
    Bytes,
}
#[derive(Clone, Copy, Debug)]
pub struct OptionSpec {
    pub name: &'static str,
    pub section: &'static str,
    pub target: &'static str,
    pub kind: Kind,
    pub help: &'static str,
}
const fn option(
    name: &'static str,
    section: &'static str,
    target: &'static str,
    kind: Kind,
    help: &'static str,
) -> OptionSpec {
    OptionSpec {
        name,
        section,
        target,
        kind,
        help,
    }
}
pub const OPTIONS: &[OptionSpec] = &[
    option(
        "prefix-cache-exact-budget",
        "cache",
        "kv_cache.exact_max_bytes",
        Kind::Bytes,
        "Exact-state retention ceiling: auto, unbounded, or IEC size; one snapshot may exceed it",
    ),
    option(
        "mmap",
        "model",
        "mmap",
        Kind::Bool,
        "Map model weights into memory",
    ),
    option(
        "mlock",
        "model",
        "mlock",
        Kind::Bool,
        "Lock model weight pages in RAM",
    ),
    option(
        "repack",
        "model",
        "repack",
        Kind::Bool,
        "Repack model tensors when supported",
    ),
    option(
        "direct-io",
        "model",
        "direct_io",
        Kind::Bool,
        "Load weights using direct I/O; takes precedence over mmap/mlock",
    ),
    option(
        "check-tensors",
        "model",
        "check_tensors",
        Kind::Bool,
        "Validate tensor data while loading",
    ),
    option(
        "no-host-buffer",
        "model",
        "no_host_buffer",
        Kind::Bool,
        "Bypass the model host buffer",
    ),
    option(
        "device",
        "execution",
        "selected_device.backend_device",
        Kind::Text,
        "Backend device name from skippy doctor",
    ),
    option(
        "split-mode",
        "execution",
        "split_mode",
        Kind::Text,
        "Multi-GPU split mode: auto, none, layer, row, tensor",
    ),
    option(
        "glm-dsa-policy",
        "execution",
        "glm_dsa_policy",
        Kind::Text,
        "GLM DSA execution policy: auto or v1",
    ),
    option(
        "main-gpu",
        "execution",
        "main_gpu",
        Kind::Unsigned,
        "GPU index for an unsplit model",
    ),
    option(
        "batch-size",
        "execution",
        "n_batch",
        Kind::Unsigned,
        "Native batch token limit",
    ),
    option(
        "microbatch-size",
        "execution",
        "n_ubatch",
        Kind::Unsigned,
        "Native microbatch token limit",
    ),
    option(
        "threads",
        "execution",
        "tuning.n_threads",
        Kind::Unsigned,
        "CPU threads for generation",
    ),
    option(
        "threads-batch",
        "execution",
        "tuning.n_threads_batch",
        Kind::Unsigned,
        "CPU threads for prompt processing",
    ),
    option(
        "op-offload",
        "execution",
        "op_offload",
        Kind::Bool,
        "Offload supported host operations to the backend",
    ),
    option(
        "kv-cache-type-k",
        "kv",
        "cache_type_k",
        Kind::Text,
        "Live key-cache precision: f16, q8_0, q4_0",
    ),
    option(
        "kv-cache-type-v",
        "kv",
        "cache_type_v",
        Kind::Text,
        "Live value-cache precision: f16, q8_0, q4_0",
    ),
    option(
        "flash-attention",
        "kv",
        "flash_attn_type",
        Kind::Text,
        "Flash Attention: auto, enabled, disabled",
    ),
    option(
        "kv-cache-offload",
        "kv",
        "kv_offload",
        Kind::Bool,
        "Offload live KV memory to the backend",
    ),
    option(
        "swa-full",
        "kv",
        "swa_full",
        Kind::Bool,
        "Use a full cache window for sliding-window attention",
    ),
    option(
        "cache-idle-slots",
        "kv",
        "cache_idle_slots",
        Kind::Unsigned,
        "Maximum retained idle sessions; zero retains none",
    ),
    option(
        "prefix-cache",
        "cache",
        "kv_cache.mode",
        Kind::Text,
        "Prompt reuse: auto, on, off, record",
    ),
    option(
        "prefix-cache-payload",
        "cache",
        "kv_cache.payload",
        Kind::Text,
        "State payload: auto, resident-kv, kv-recurrent, full-state",
    ),
    option(
        "prefix-cache-codec",
        "cache",
        "kv_cache.codec",
        Kind::Text,
        "Durable representation: native or experimental cachegen",
    ),
    option(
        "prefix-cache-budget",
        "cache",
        "kv_cache.max_bytes",
        Kind::Bytes,
        "Retention target: auto, unbounded, or IEC size; exact snapshots may exceed it",
    ),
    option(
        "prefix-cache-ram",
        "cache",
        "kv_cache.l2_max_bytes",
        Kind::Bytes,
        "Host-RAM tier: off or IEC size; requires disk caching",
    ),
    option(
        "prefix-cache-max-entries",
        "cache",
        "kv_cache.max_entries",
        Kind::Unsigned,
        "Maximum retained prefix entries",
    ),
    option(
        "prefix-cache-min-tokens",
        "cache",
        "kv_cache.min_tokens",
        Kind::Unsigned,
        "Minimum prefix length to record or reuse",
    ),
    option(
        "prefix-cache-stride-tokens",
        "cache",
        "kv_cache.shared_prefix_stride_tokens",
        Kind::Unsigned,
        "Shared-prefix checkpoint spacing in tokens",
    ),
    option(
        "prefix-cache-record-limit",
        "cache",
        "kv_cache.shared_prefix_record_limit",
        Kind::Unsigned,
        "Maximum shared-prefix checkpoints per recording",
    ),
    option(
        "continuous-batching",
        "scheduling",
        "tuning.continuous_batching",
        Kind::Bool,
        "Allow the iteration scheduler to serve concurrent lanes",
    ),
    option(
        "pipeline-decode-groups",
        "scheduling",
        "tuning.pipeline_decode_groups",
        Kind::Unsigned,
        "Number of decode dispatch groups",
    ),
    option(
        "generation-signal-window",
        "scheduling",
        "generation_signal_window",
        Kind::Unsigned,
        "Generation signal observation window in tokens",
    ),
    option(
        "projector-gpu",
        "media",
        "projector_use_gpu",
        Kind::Bool,
        "Run the multimodal projector on the GPU",
    ),
    option(
        "media-marker",
        "media",
        "media_marker",
        Kind::Text,
        "Media marker used by the model template",
    ),
    option(
        "image-min-tokens",
        "media",
        "image_min_tokens",
        Kind::Unsigned,
        "Minimum image token budget",
    ),
    option(
        "image-max-tokens",
        "media",
        "image_max_tokens",
        Kind::Unsigned,
        "Maximum image token budget",
    ),
    option(
        "media-batch-max-tokens",
        "media",
        "batch_max_tokens",
        Kind::Unsigned,
        "Maximum media processing batch token count",
    ),
    option(
        "temperature",
        "sampling",
        "request.temperature",
        Kind::Number,
        "Default sampling temperature",
    ),
    option(
        "top-p",
        "sampling",
        "request.top_p",
        Kind::Number,
        "Default nucleus sampling probability",
    ),
    option(
        "min-p",
        "sampling",
        "request.min_p",
        Kind::Number,
        "Default minimum token probability",
    ),
    option(
        "typical-p",
        "sampling",
        "request.typical_p",
        Kind::Number,
        "Default typical sampling probability",
    ),
    option(
        "top-nsigma",
        "sampling",
        "request.top_nsigma",
        Kind::Number,
        "Default top-n-sigma sampling bound",
    ),
    option(
        "presence-penalty",
        "sampling",
        "request.presence_penalty",
        Kind::Number,
        "Default presence penalty",
    ),
    option(
        "frequency-penalty",
        "sampling",
        "request.frequency_penalty",
        Kind::Number,
        "Default frequency penalty",
    ),
    option(
        "repeat-penalty",
        "sampling",
        "request.repeat_penalty",
        Kind::Number,
        "Default repetition penalty",
    ),
    option(
        "dynatemp-range",
        "sampling",
        "request.dynatemp_range",
        Kind::Number,
        "Dynamic temperature range",
    ),
    option(
        "dynatemp-exponent",
        "sampling",
        "request.dynatemp_exponent",
        Kind::Number,
        "Dynamic temperature exponent",
    ),
    option(
        "mirostat-entropy",
        "sampling",
        "request.mirostat_entropy",
        Kind::Number,
        "Mirostat target entropy",
    ),
    option(
        "mirostat-learning-rate",
        "sampling",
        "request.mirostat_learning_rate",
        Kind::Number,
        "Mirostat learning rate",
    ),
    option(
        "top-k",
        "sampling",
        "request.top_k",
        Kind::Integer,
        "Default top-k token count",
    ),
    option(
        "repeat-last-n",
        "sampling",
        "request.repeat_last_n",
        Kind::Integer,
        "Repetition history length; -1 uses the runtime default",
    ),
    option(
        "mirostat-mode",
        "sampling",
        "request.mirostat_mode",
        Kind::Integer,
        "Mirostat mode: 0, 1, or 2",
    ),
    option(
        "seed",
        "sampling",
        "request.seed",
        Kind::Unsigned,
        "Default sampling seed",
    ),
    option(
        "request-max-tokens",
        "sampling",
        "request.max_tokens",
        Kind::Unsigned,
        "Operator default output limit, overridden by an explicit request",
    ),
    option(
        "ignore-eos",
        "sampling",
        "request.ignore_eos",
        Kind::Bool,
        "Ignore end-of-sequence tokens by default",
    ),
    option(
        "stop",
        "sampling",
        "request.stop",
        Kind::Json,
        "JSON array of default stop strings; @file loads JSON",
    ),
    option(
        "logit-bias",
        "sampling",
        "request.logit_bias",
        Kind::Json,
        "JSON map of token IDs to biases; @file loads JSON",
    ),
    option(
        "samplers",
        "sampling",
        "request.samplers",
        Kind::Json,
        "JSON array defining the sampler order; @file loads JSON",
    ),
    option(
        "sampler-sequence",
        "sampling",
        "request.sampler_sequence",
        Kind::Text,
        "Compact sampler sequence",
    ),
    option(
        "dry-multiplier",
        "sampling",
        "request.dry.multiplier",
        Kind::Number,
        "DRY repetition penalty multiplier",
    ),
    option(
        "dry-base",
        "sampling",
        "request.dry.base",
        Kind::Number,
        "DRY exponential base",
    ),
    option(
        "xtc-probability",
        "sampling",
        "request.xtc.probability",
        Kind::Number,
        "XTC sampling probability",
    ),
    option(
        "xtc-threshold",
        "sampling",
        "request.xtc.threshold",
        Kind::Number,
        "XTC probability threshold",
    ),
    option(
        "dry-allowed-length",
        "sampling",
        "request.dry.allowed_length",
        Kind::Integer,
        "DRY allowed repetition length",
    ),
    option(
        "dry-penalty-last-n",
        "sampling",
        "request.dry.penalty_last_n",
        Kind::Integer,
        "DRY history length; -1 uses the runtime default",
    ),
    option(
        "dry-sequence-breakers",
        "sampling",
        "request.dry.sequence_breakers",
        Kind::Json,
        "JSON array of DRY sequence breakers; @file loads JSON",
    ),
    option(
        "reasoning-format",
        "chat",
        "request.reasoning_format",
        Kind::Text,
        "Reasoning format: auto, none, deepseek, deepseek-legacy, hidden",
    ),
    option(
        "reasoning",
        "chat",
        "request.reasoning_enabled",
        Kind::Text,
        "Reasoning default: auto, enabled, disabled",
    ),
    option(
        "reasoning-budget",
        "chat",
        "request.reasoning_budget",
        Kind::Json,
        "JSON: \"auto\", \"unrestricted\", {\"tokens\":N}, or {\"effort\":\"high\"}",
    ),
    option(
        "chat-template-kwargs",
        "chat",
        "request.chat_template_kwargs",
        Kind::Json,
        "JSON template arguments; @file loads JSON",
    ),
    option(
        "prefill-assistant",
        "chat",
        "request.prefill_assistant",
        Kind::Json,
        "JSON assistant string or message object; @file loads JSON",
    ),
    option(
        "json-schema",
        "chat",
        "request.json_schema",
        Kind::Json,
        "Default structured-output JSON schema; @file loads JSON",
    ),
    option(
        "system-prompt",
        "chat",
        "request.system_prompt",
        Kind::Content,
        "Default system prompt; @file loads UTF-8 text",
    ),
    option(
        "chat-template",
        "chat",
        "request.chat_template",
        Kind::Content,
        "Chat template; @file loads UTF-8 text",
    ),
    option(
        "grammar",
        "chat",
        "request.grammar",
        Kind::Content,
        "Default grammar; @file loads UTF-8 text",
    ),
    option(
        "allow-request-chat-template",
        "chat",
        "request.allow_request_chat_template",
        Kind::Bool,
        "Let requests supply their own chat template (trusts every caller)",
    ),
    option(
        "jinja",
        "chat",
        "request.jinja",
        Kind::Bool,
        "Use the Jinja template engine",
    ),
    option(
        "skip-chat-parsing",
        "chat",
        "request.skip_chat_parsing",
        Kind::Bool,
        "Skip structured chat-output parsing",
    ),
    option(
        "speculative-strategy",
        "speculative",
        "spec.requested_strategy",
        Kind::Text,
        "Speculation: auto, disabled, draft-model, native-mtp, ngram, mtp-ngram",
    ),
    option(
        "draft-device",
        "speculative",
        "spec.draft_device",
        Kind::Text,
        "Backend device for the draft model",
    ),
    option(
        "draft-cache-type-k",
        "speculative",
        "spec.draft_cache_type_k",
        Kind::Text,
        "Draft key-cache precision: f16, q8_0, q4_0",
    ),
    option(
        "draft-cache-type-v",
        "speculative",
        "spec.draft_cache_type_v",
        Kind::Text,
        "Draft value-cache precision: f16, q8_0, q4_0",
    ),
    option(
        "ngram-kind",
        "speculative",
        "spec.ngram.kind",
        Kind::Text,
        "N-gram proposer: cache or suffix",
    ),
    option(
        "native-mtp",
        "speculative",
        "spec.native_mtp.enabled",
        Kind::Bool,
        "Enable native multi-token prediction",
    ),
    option(
        "mtp-suppress-cooldown-drafts",
        "speculative",
        "spec.native_mtp.suppress_cooldown_drafts",
        Kind::Bool,
        "Suppress drafts during MTP rejection cooldown",
    ),
    option(
        "ngram-fallback-draft",
        "speculative",
        "spec.ngram_fallback_draft",
        Kind::Bool,
        "Use the draft model after an N-gram miss; requires pipelined verification",
    ),
    option(
        "draft-threads",
        "speculative",
        "spec.draft_threads",
        Kind::Unsigned,
        "CPU threads for the draft model",
    ),
    option(
        "mtp-max-tokens",
        "speculative",
        "spec.native_mtp.max_draft_tokens",
        Kind::Unsigned,
        "Maximum native MTP proposal length",
    ),
    option(
        "mtp-min-tokens",
        "speculative",
        "spec.native_mtp.min_draft_tokens",
        Kind::Unsigned,
        "Minimum native MTP proposal length",
    ),
    option(
        "mtp-reject-cooldown-tokens",
        "speculative",
        "spec.native_mtp.reject_cooldown_tokens",
        Kind::Unsigned,
        "Cooldown after native MTP rejection",
    ),
    option(
        "mtp-suppress-cooldown-draft-limit",
        "speculative",
        "spec.native_mtp.suppress_cooldown_draft_limit",
        Kind::Unsigned,
        "Maximum suppressed cooldown drafts",
    ),
    option(
        "ngram-min",
        "speculative",
        "spec.ngram.min_ngram",
        Kind::Unsigned,
        "Minimum matching N-gram length",
    ),
    option(
        "ngram-max",
        "speculative",
        "spec.ngram.max_ngram",
        Kind::Unsigned,
        "Maximum matching N-gram length",
    ),
    option(
        "ngram-max-tokens",
        "speculative",
        "spec.ngram.max_proposal_tokens",
        Kind::Unsigned,
        "Maximum N-gram proposal length",
    ),
    option(
        "ngram-extension-max-tokens",
        "speculative",
        "spec.extension.max_tokens",
        Kind::Unsigned,
        "Maximum N-gram extension after an MTP prefix",
    ),
    option(
        "verify-min-tokens",
        "speculative",
        "spec.verify_window.min_tokens",
        Kind::Unsigned,
        "Minimum verification window",
    ),
    option(
        "verify-max-tokens",
        "speculative",
        "spec.verify_window.max_tokens",
        Kind::Unsigned,
        "Maximum verification window",
    ),
    option(
        "verify-pipeline-depth",
        "speculative",
        "spec.verify_window.pipeline_depth",
        Kind::Unsigned,
        "Maximum outstanding verification windows",
    ),
    option(
        "verify-runahead-max-tokens",
        "speculative",
        "spec.verify_window.runahead_max_tokens",
        Kind::Unsigned,
        "Outstanding speculative-token budget; zero uses pipeline depth",
    ),
    option(
        "draft-acceptance-threshold",
        "speculative",
        "spec.draft_acceptance_threshold",
        Kind::Number,
        "Minimum accepted fraction of a draft window",
    ),
    option(
        "draft-split-probability",
        "speculative",
        "spec.draft_split_probability",
        Kind::Number,
        "Probability of splitting a draft proposal",
    ),
    option(
        "guardrails-tool-retries",
        "api",
        "guardrails.max_tool_retries",
        Kind::Unsigned,
        "Maximum retries for invalid tool output",
    ),
    option(
        "guardrails-structured-retries",
        "api",
        "guardrails.max_structured_retries",
        Kind::Unsigned,
        "Maximum retries for invalid structured output",
    ),
    option(
        "compact-context-limit",
        "api",
        "compaction.context_limit_tokens",
        Kind::Unsigned,
        "Context token limit used by compaction",
    ),
    option(
        "compact-trigger-percent",
        "api",
        "compaction.trigger_ratio_percent",
        Kind::Unsigned,
        "Context utilisation percent that triggers compaction",
    ),
    option(
        "compact-target-percent",
        "api",
        "compaction.target_ratio_percent",
        Kind::Unsigned,
        "Target utilisation percent after compaction",
    ),
    option(
        "guardrails-retry-exhaustion",
        "api",
        "guardrails.retry_exhaustion_mode",
        Kind::Text,
        "Retry exhaustion: error or pass-last-text",
    ),
    option(
        "guardrails-reserved-tool-prefix",
        "api",
        "guardrails.reserved_tool_prefix",
        Kind::Text,
        "Tool-name prefix reserved by guardrails",
    ),
    option(
        "guardrails-all-models",
        "api",
        "guardrails.apply_to_all_models",
        Kind::Bool,
        "Apply guardrails to every model",
    ),
    option(
        "compact",
        "api",
        "compaction.enabled",
        Kind::Bool,
        "Automatically compact chat history",
    ),
    option(
        "compact-drop-reasoning",
        "api",
        "compaction.allow_reasoning_drop",
        Kind::Bool,
        "Allow compaction to drop historical reasoning",
    ),
    option(
        "guardrails-small-model-threshold",
        "api",
        "guardrails.small_param_threshold_b",
        Kind::Number,
        "Small-model threshold in billions of parameters",
    ),
    option(
        "activation-codec",
        "distributed",
        "activation_codec",
        Kind::Text,
        "Stage activation codec: raw-f32-v1, f16-rne-v1, bf16-rne-v1, s8-row-f32-rne-v1",
    ),
    option(
        "activation-codec-policy",
        "distributed",
        "activation_codec_policy",
        Kind::Text,
        "Stage activation policy: fixed or auto-lossless-v1",
    ),
];
