#!/usr/bin/env bash
# Cargo metadata owns changed-path selection and reverse dependencies.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/lib/automation.sh
source "$REPO_ROOT/scripts/lib/automation.sh"

# Rust repository and CI consistency checks read this shared fallback roster.
# shellcheck disable=SC2034
WORKSPACE_MEMBERS=(
  "mesh-llm"
  "mesh-llm-analytics"
  "mesh-llm-build-info"
  "mesh-llm-cli"
  "mesh-llm-commands"
  "mesh-llm-config"
  "mesh-llm-events"
  "skippy-gpu-bench"
  "mesh-llm-host-runtime"
  "mesh-llm-control-api"
  "mesh-llm-skippy-adapter"
  "skippy-hardware-profile"
  "mesh-llm-identity"
  "mesh-llm-log-store"
  "skippy-native-runtime"
  "mesh-llm-payments"
  "mesh-llm-payments-types"
  "mesh-llm-wallet"
  "mesh-llm-protocol"
  "mesh-llm-transport"
  "mesh-llm-membership"
  "mesh-llm-release-footer"
  "mesh-llm-routing"
  "mesh-llm-runtime-event-contracts"
  "skippy-runtime-install"
  "mesh-llm-sdk"
  "skippy-guardrails"
  "mesh-llm-system"
  "mesh-llm-types"
  "mesh-llm-console-server"
  "mesh-llm-embedded-runtime"
  "mesh-llm-tui"
  "mesh-llm-ui"
  "mesh-llm-plugin"
  "mesh-llm-skills"
  "mesh-llm-plugin-manager"
  "mesh-llm-client"
  "mesh-mixture-of-agents"
  "mesh-llm-moa-plugin"
  "mesh-native-serving-plugin-api"
  "mesh-native-serving-plugin-host"
  "mesh-llm-api-client"
  "mesh-llm-api-server"
  "mesh-llm-node"
  "mesh-llm-ffi"
  "mesh-llm-nodejs"
  "mesh-llm-test-harness"
  "skippy-model-ref"
  "skippy-model-artifact"
  "skippy-model-hf"
  "skippy-hf-hub"
  "skippy-model-resolver"
  "skippy-protocol"
  "skippy-events"
  "skippy-tokenizer"
  "skippy-coordinator"
  "skippy-topology"
  "skippy-cache"
  "skippy-metrics"
  "skippy-inference-api"
  "skippy-ffi"
  "skippy-model"
  "skippy-package-format"
  "skippy-runtime"
  "skippy-scheduler"
  "skippy-api"
  "skippy-serving"
  "skippy-cli"
  "skippy-commands"
  "skippy-config"
  "metrics-server"
  "skippy-package-builder"
  "skippy-quantize"
  "skippy-model-package"
  "skippy-correctness"
  "llama-spec-bench"
  "skippy-bench"
  "xtask"
)

# Preserve invocation cwd: Cargo discovers the caller-selected workspace there.
mesh_automation repository affected-crates "$@"
