#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path
import re
import sys
from typing import Final


HEADER: Final = "<!-- Generated by scripts/generate-runtime-event-inventory.py. -->\n"
INLINE_KEY_PATTERN: Final = re.compile(r"(?<![\w\"])\b([a-z_]+)\s*=")


class InventoryContractError(RuntimeError):
    pass


def load_inventory(path: Path) -> dict:
    root = {}
    current = root
    assignment = ""
    bracket_depth = 0
    for source_line in path.read_text(encoding="utf-8").splitlines():
        line = source_line.strip()
        if not line or line.startswith("#"):
            continue
        if not assignment and line.startswith("[["):
            table_name = line[2:-2]
            table = {}
            root.setdefault(table_name, []).append(table)
            current = table
            continue
        if not assignment and line.startswith("["):
            table_name = line[1:-1]
            current = root.setdefault(table_name, {})
            continue
        assignment = f"{assignment} {line}".strip()
        bracket_depth += line.count("[") - line.count("]")
        if bracket_depth > 0:
            continue
        key, value = assignment.split("=", 1)
        normalized = INLINE_KEY_PATTERN.sub(r'"\1":', value.strip())
        current[key.strip()] = ast.literal_eval(normalized)
        assignment = ""
    if assignment:
        raise RuntimeError(f"unterminated TOML assignment: {assignment}")
    return root


def resolved_events(inventory: dict) -> list[dict]:
    families = {family["section"]: family for family in inventory["families"]}
    terminal = set(inventory["catalog"]["terminal_event_ids"])
    progress = set(inventory["catalog"]["progress_event_ids"])
    event_ids = {
        event_id
        for bullet in inventory["catalog"]["spec_bullets"]
        for event_id in bullet["event_ids"]
    }
    profiles = _projection_profiles(inventory)
    overrides = _projection_overrides(inventory, event_ids, profiles)
    events = {}
    for bullet in inventory["catalog"]["spec_bullets"]:
        family = families.get(bullet["section"])
        if family is None:
            raise InventoryContractError(
                f"unresolved event family: {bullet['section']}"
            )
        for event_id in bullet["event_ids"]:
            if event_id in terminal:
                delivery = "terminal"
            elif event_id in progress:
                delivery = "progress"
            else:
                delivery = family["default_delivery_class"]
            profile_name = overrides.get(
                event_id, family.get("default_projection_profile")
            )
            if profile_name is None:
                raise InventoryContractError(f"missing event-key entry: {event_id}")
            profile_keys = profiles.get(profile_name)
            if profile_keys is None:
                raise InventoryContractError(
                    f"unresolved projection profile: {profile_name}"
                )
            projected_keys = (
                inventory["projected_envelope_keys"]
                + inventory["base_projected_event_keys"]
                + profile_keys
            )
            events[event_id] = {
                "id": event_id,
                "section": bullet["section"],
                "deliveryClass": delivery,
                "privacyClass": family["privacy_class"],
                "projectedKeys": projected_keys,
                "projectionProfile": profile_name,
                "producerSymbols": family["producer_symbols"],
                "sourcePaths": family["source_paths"],
                "authoritativeOutcome": family["authoritative_outcome"],
                "reducerEffect": family["reducer_effect"],
                "projection": family["projection"],
                "test": family["test"],
                "migrationTask": family["migration_task"],
            }
    return [events[event_id] for event_id in sorted(events)]


def _projection_profiles(inventory: dict) -> dict[str, list[str]]:
    allowed = set(inventory["projected_event_keys"])
    forbidden = set(inventory["forbidden_projection_keys"])
    profiles = {}
    for profile in inventory["projection_profiles"]:
        name = profile["name"]
        keys = profile["keys"]
        forbidden_keys = forbidden.intersection(keys)
        if forbidden_keys:
            raise InventoryContractError(
                f"forbidden projected key: {sorted(forbidden_keys)[0]}"
            )
        unknown_keys = set(keys).difference(allowed)
        if unknown_keys:
            raise InventoryContractError(
                f"unknown projected key: {sorted(unknown_keys)[0]}"
            )
        if set(keys) == allowed:
            raise InventoryContractError(f"overbroad projection profile: {name}")
        profiles[name] = keys
    return profiles


def _projection_overrides(
    inventory: dict, event_ids: set[str], profiles: dict[str, list[str]]
) -> dict[str, str]:
    overrides = {}
    for override in inventory["event_projection_overrides"]:
        profile = override["profile"]
        if profile not in profiles:
            raise InventoryContractError(f"unresolved projection profile: {profile}")
        for event_id in override["event_ids"]:
            if event_id not in event_ids:
                raise InventoryContractError(f"unresolved event kind: {event_id}")
            if event_id in overrides:
                raise InventoryContractError(
                    f"duplicate event projection override: {event_id}"
                )
            overrides[event_id] = profile
    return overrides


def render_typescript(inventory: dict) -> str:
    payload = {
        "schemaVersion": inventory["schema_version"],
        "specSha256": inventory["spec_sha256"],
        "reasonCodes": inventory["reason_codes"],
        "events": resolved_events(inventory),
    }
    return (
        "// Generated by scripts/generate-runtime-event-inventory.py.\n"
        "export const runtimeEventInventory = "
        + json.dumps(payload, indent=2, ensure_ascii=True)
        + " as const;\n"
    )


def render_markdown(inventory: dict) -> str:
    events = resolved_events(inventory)
    lines = [
        HEADER.rstrip(),
        "# Runtime event inventory",
        "",
        f"Schema version: `{inventory['schema_version']}`  ",
        f"Ratified spec SHA-256: `{inventory['spec_sha256']}`  ",
        f"Atomic event IDs: `{len(events)}`",
        "",
        "## Families",
        "",
        "| Spec | Rust enum | Owning crates | Producer symbols | Privacy | Default delivery | Migration task |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for family in inventory["families"]:
        lines.append(
            f"| {family['section']} | `{family['enum_name']}` | "
            f"{', '.join(f'`{name}`' for name in family['owning_crates'])} | "
            f"{', '.join(f'`{name}`' for name in family['producer_symbols'])} | "
            f"`{family['privacy_class']}` | `{family['default_delivery_class']}` | "
            f"{family['migration_task']} |"
        )
    lines.extend(
        [
            "",
            "## Stable event IDs",
            "",
            "| Event ID | Spec | Delivery | Privacy | Projection profile | Projected keys |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for event in events:
        lines.append(
            f"| `{event['id']}` | {event['section']} | "
            f"`{event['deliveryClass']}` | `{event['privacyClass']}` | "
            f"`{event['projectionProfile']}` | "
            f"{', '.join(f'`{key}`' for key in event['projectedKeys'])} |"
        )
    lines.extend(
        [
            "",
            "## Amendment procedure",
            "",
            inventory["amendment_procedure"],
            "",
        ]
    )
    return "\n".join(lines)


def update_or_check(outputs: dict[Path, str], check: bool) -> int:
    stale = []
    for path, rendered in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == rendered:
            continue
        if check:
            stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered, encoding="utf-8")
        print(f"generated {path}")
    for path in stale:
        print(f"stale generated runtime-event inventory: {path}", file=sys.stderr)
    return int(bool(stale))


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="Generate runtime-event inventory docs and TypeScript fixtures."
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    inventory = load_inventory(
        root / "crates/mesh-llm-runtime-event-contracts/inventory/runtime_events.toml"
    )
    outputs = {
        root / "docs/design/RUNTIME_EVENT_INVENTORY.md": render_markdown(inventory),
        root
        / "crates/mesh-llm-runtime-event-contracts/fixtures/runtime_event_inventory.ts": render_typescript(
            inventory
        ),
    }
    return update_or_check(outputs, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
