use anyhow::{Context, Result};
use hf_hub::{
    HFClient,
    buckets::{BucketDownload, BucketTreeEntry, BucketUpload},
};
use sha2::{Digest, Sha256};

/// The embedded canonical job script.
pub const EMBEDDED_SCRIPT: &str = include_str!("scripts/split-model-job.sh");

// Generated by build.rs — provides EMBEDDED_SCRIPT_SHA256 and EMBEDDED_SCRIPT_SIZE.
include!(concat!(env!("OUT_DIR"), "/script_hash.rs"));

/// Result of comparing the bucket script against the embedded version.
#[derive(Debug)]
pub struct ScriptFreshness {
    /// Size of the script in the bucket (bytes).
    pub bucket_size: u64,
    /// Size of the embedded script (bytes).
    pub expected_size: u64,
    /// Whether the bucket script matches the embedded version.
    pub is_current: bool,
    /// Human-readable reason when the script is not current.
    pub mismatch_reason: Option<String>,
}

/// Compare the bucket script's size against the embedded version.
///
/// If sizes match, downloads the ~10 KB file and verifies the SHA-256 hash.
pub async fn check_bucket_script(client: &HFClient) -> Result<ScriptFreshness> {
    let bucket = client.bucket("meshllm", "layer-split-output");
    let paths = vec!["split-model-job.sh".to_string()];

    let entries = bucket
        .get_paths_info()
        .paths(paths)
        .send()
        .await
        .context("check bucket script metadata")?;

    let bucket_size = entries
        .into_iter()
        .find_map(|entry| match entry {
            BucketTreeEntry::File { size, .. } => Some(size),
            _ => None,
        })
        .context("split-model-job.sh not found in meshllm/layer-split-output bucket")?;

    if bucket_size != EMBEDDED_SCRIPT_SIZE {
        return Ok(ScriptFreshness {
            bucket_size,
            expected_size: EMBEDDED_SCRIPT_SIZE,
            is_current: false,
            mismatch_reason: Some(format!(
                "size differs: bucket has {bucket_size} bytes, embedded script has {expected_size} bytes",
                expected_size = EMBEDDED_SCRIPT_SIZE
            )),
        });
    }

    // Sizes match — download to a unique temp file and verify SHA-256.
    let tmp_dir = tempfile::tempdir().context("create bucket script check temp dir")?;
    let tmp_path = tmp_dir.path().join("split-model-job.sh");

    bucket
        .download_files()
        .files(vec![BucketDownload::new(
            "split-model-job.sh",
            tmp_path.clone(),
        )])
        .send()
        .await
        .context("download bucket script for hash verification")?;

    let bytes = std::fs::read(&tmp_path).context("read downloaded bucket script")?;
    let hash = Sha256::digest(&bytes);
    let hex: String = hash.iter().map(|b| format!("{b:02x}")).collect();

    let is_current = hex == EMBEDDED_SCRIPT_SHA256;

    Ok(ScriptFreshness {
        bucket_size,
        expected_size: EMBEDDED_SCRIPT_SIZE,
        is_current,
        mismatch_reason: (!is_current).then(|| {
            format!(
                "sha256 differs: bucket has {hex}, embedded script has {expected}",
                expected = EMBEDDED_SCRIPT_SHA256
            )
        }),
    })
}

/// Upload the embedded script to the meshllm bucket.
///
/// Requires meshllm org write access.
pub async fn update_bucket_script(client: &HFClient) -> Result<()> {
    let bucket = client.bucket("meshllm", "layer-split-output");

    // Write embedded script to a unique temp file for upload.
    let tmp_dir = tempfile::tempdir().context("create bucket script upload temp dir")?;
    let tmp_path = tmp_dir.path().join("split-model-job.sh");
    std::fs::write(&tmp_path, EMBEDDED_SCRIPT)?;

    bucket
        .upload_files()
        .files(vec![BucketUpload::new(
            tmp_path.clone(),
            "split-model-job.sh",
        )])
        .send()
        .await
        .context("upload script to meshllm/layer-split-output bucket")?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::EMBEDDED_SCRIPT;

    #[test]
    fn embedded_script_prints_mesh_llm_repo_shorthand() {
        assert!(EMBEDDED_SCRIPT.contains("mesh-llm serve --model ${TARGET_REPO} --split"));
        assert!(!EMBEDDED_SCRIPT.contains(r#"mesh-llm serve --model "hf://${TARGET_REPO}""#));
        assert!(!EMBEDDED_SCRIPT.contains("mesh-llm serve --model hf://${TARGET_REPO}"));
    }

    #[test]
    fn embedded_script_writes_rich_model_card() {
        assert!(EMBEDDED_SCRIPT.contains("SOURCE_PIPELINE_TAG"));
        assert!(EMBEDDED_SCRIPT.contains("PACKAGE_EXPERIMENTAL"));
        // Card content and license fallback are exercised by layer_job's renderer
        // and source tests. This owner verifies the embedded job calls that path.
        assert!(
            EMBEDDED_SCRIPT.contains(
                r#""$LAYER_JOB" prepare-card --manifest "$PACKAGE_DIR/model-package.json""#
            )
        );
        assert!(
            EMBEDDED_SCRIPT.contains(r#"--pipeline-tag "${SOURCE_PIPELINE_TAG:-text-generation}""#)
        );
        assert!(EMBEDDED_SCRIPT.contains(r#"--mesh-llm-ref "${MESH_LLM_REF:-main}""#));
        assert!(EMBEDDED_SCRIPT.contains(r#"CARD_EXPERIMENTAL_ARGS+=(--experimental)"#));
        assert!(EMBEDDED_SCRIPT.contains(r#""${CARD_EXPERIMENTAL_ARGS[@]}""#));
        assert!(EMBEDDED_SCRIPT.contains(
            r#"publish_layer_file "${LOCAL_WORK_DIR}/model-card/README.md" README.md main"#
        ));
    }

    #[test]
    fn embedded_script_streams_package_artifacts_to_hub() {
        assert!(EMBEDDED_SCRIPT.contains("SOURCE_QUANT"));
        assert!(EMBEDDED_SCRIPT.contains("SOURCE_TOTAL_BYTES"));
        assert!(EMBEDDED_SCRIPT.contains("Estimated fallback /bucket cache needed"));
        assert!(EMBEDDED_SCRIPT.contains("estimate_bucket_workspace_bytes"));
        assert!(
            EMBEDDED_SCRIPT.contains(r#"PACKAGE_DIR="${PACKAGE_DIR:-${LOCAL_WORK_DIR}/package}""#)
        );
        assert!(EMBEDDED_SCRIPT.contains(
            "refusing to continue (unset PACKAGE_DIR_ALLOW_BUCKET to require local staging)"
        ));
        assert!(
            EMBEDDED_SCRIPT
                .contains(r#"HF_XET_CACHE="${HF_XET_CACHE:-${LOCAL_WORK_DIR}/xet-cache}""#)
        );
        assert!(EMBEDDED_SCRIPT.contains(r#"HF_HUB_DISABLE_XET="${HF_HUB_DISABLE_XET:-1}""#));
        assert!(EMBEDDED_SCRIPT.contains(r#"JOB_TMP_DIR="${JOB_TMP_DIR:-${LOCAL_WORK_DIR}/tmp}""#));
        assert!(EMBEDDED_SCRIPT.contains(r#"LOCAL_WORK_DIR="${LOCAL_WORK_DIR:-/tmp/"#));
        assert!(
            EMBEDDED_SCRIPT.contains(r#"BUILD_TMP_DIR="${BUILD_TMP_DIR:-${LOCAL_WORK_DIR}/tmp}""#)
        );
        assert!(EMBEDDED_SCRIPT.contains(r#"TMPDIR="$BUILD_TMP_DIR""#));
        assert!(EMBEDDED_SCRIPT.contains(r#"TMPDIR="$JOB_TMP_DIR""#));
        assert!(EMBEDDED_SCRIPT.contains("export TMPDIR TEMP TMP"));
        assert!(
            EMBEDDED_SCRIPT.contains(
                r#"CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-${LOCAL_WORK_DIR}/cargo-target}""#
            )
        );
        assert!(
            EMBEDDED_SCRIPT.contains(
                r#"rm -rf "$BUILD_DIR" "$CARGO_TARGET_DIR" "$CARGO_HOME" "$RUSTUP_HOME""#
            )
        );
        assert!(EMBEDDED_SCRIPT.contains(r#"SOURCE_REF="${SOURCE_REPO}:${SOURCE_QUANT}""#));
        assert!(
            EMBEDDED_SCRIPT
                .contains(r#"SOURCE_REF="${SOURCE_REPO}@${SOURCE_REVISION}:${SOURCE_QUANT}""#)
        );
        assert!(EMBEDDED_SCRIPT.contains("log_storage_snapshot"));
        assert!(EMBEDDED_SCRIPT.contains("start_heartbeat"));
        assert!(EMBEDDED_SCRIPT.contains("Starting write-package"));
        assert!(EMBEDDED_SCRIPT.contains(r#""${LAYER_JOB}" upload --confirm"#));
        assert!(EMBEDDED_SCRIPT.contains("SKIPPY_PACKAGE_ARTIFACT_PATH"));
        assert!(EMBEDDED_SCRIPT.contains("SKIPPY_PACKAGE_ARTIFACT_RELATIVE_PATH"));
        assert!(EMBEDDED_SCRIPT.contains("ARTIFACT_UPLOAD_ATTEMPTS"));
        assert!(EMBEDDED_SCRIPT.contains(r#"--maximum-attempts "${ARTIFACT_UPLOAD_ATTEMPTS:-8}""#));
        assert!(EMBEDDED_SCRIPT.contains("--unlink-after-success"));
        assert!(EMBEDDED_SCRIPT.contains(r#"--after-artifact-command "$ARTIFACT_UPLOAD_HOOK""#));
        assert!(!EMBEDDED_SCRIPT.contains("api.upload_folder"));
        assert!(EMBEDDED_SCRIPT.contains("TARGET_UPLOAD_REVISION"));
        assert!(EMBEDDED_SCRIPT.contains("promote-layer-package-snapshot"));
        assert!(EMBEDDED_SCRIPT.contains("Atomically promoted replacement snapshot to main"));
        assert!(EMBEDDED_SCRIPT.contains(r#"MOUNTED_SOURCE_PATH="/source/${SOURCE_FILE}""#));
        assert!(EMBEDDED_SCRIPT.contains(r#"WRITE_PACKAGE_INPUT="$MOUNTED_SOURCE_PATH""#));
        assert!(EMBEDDED_SCRIPT.contains(r#"--source-file "$SOURCE_FILE""#));
        assert!(EMBEDDED_SCRIPT.contains("SOURCE_PROJECTOR_FILES"));
        assert!(
            EMBEDDED_SCRIPT
                .contains(r#"WRITE_PACKAGE_PROJECTOR_ARGS+=(--projector "$PROJECTOR_PATH")"#)
        );
        assert!(EMBEDDED_SCRIPT.contains(r#""${WRITE_PACKAGE_PROJECTOR_ARGS[@]}""#));
        assert!(EMBEDDED_SCRIPT.contains("Pinned source revision"));
        assert!(EMBEDDED_SCRIPT.contains("config.json"));
        assert!(EMBEDDED_SCRIPT.contains("hf_quant_config.json"));
        assert!(
            EMBEDDED_SCRIPT.contains(
                r#"WRITE_PACKAGE_METADATA_ARGS+=(--publisher-metadata "$METADATA_PATH")"#
            )
        );
        assert!(EMBEDDED_SCRIPT.contains(r#""${WRITE_PACKAGE_METADATA_ARGS[@]}""#));
        assert!(EMBEDDED_SCRIPT.contains(r#"time "$SLICER" write-package "$WRITE_PACKAGE_INPUT""#));
        assert!(!EMBEDDED_SCRIPT.contains(r#"time $SLICER write-package "$SOURCE_PATH""#));
    }

    #[test]
    fn embedded_script_preserves_catalog_source_revision() {
        // Native catalog projection tests cover dict/list variants and the
        // retained immutable source revision; this verifies caller forwarding.
        assert!(EMBEDDED_SCRIPT.contains(
            r#""$LAYER_JOB" update-catalog --confirm --manifest "$PACKAGE_DIR/model-package.json""#
        ));
        assert!(EMBEDDED_SCRIPT.contains(r#"--source-repo "$SOURCE_REPO" --source-revision "$SOURCE_REVISION" --source-file "$SOURCE_FILE""#));
        assert!(EMBEDDED_SCRIPT.contains(r#""${CATALOG_PR_ARGS[@]}""#));
    }

    #[test]
    fn embedded_script_forwards_generation_defaults_to_package_writer() {
        assert!(EMBEDDED_SCRIPT.contains("GENERATION_DEFAULTS_JSON"));
        assert!(EMBEDDED_SCRIPT.contains("generation-defaults.json"));
        assert!(EMBEDDED_SCRIPT.contains("--generation-defaults"));
    }
}
