use super::{Event, Inventory};
use crate::command::DynResult;
use serde::Serialize;

fn quoted(values: &[String]) -> String {
    values
        .iter()
        .map(|value| format!("`{value}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

pub(super) fn markdown(inventory: &Inventory, events: &[Event<'_>]) -> String {
    let mut lines = vec![
        "<!-- Generated by scripts/generate-runtime-event-inventory.py. -->".to_owned(),
        "# Runtime event inventory".into(),
        String::new(),
        format!("Schema version: `{}`  ", inventory.schema_version),
        format!("Ratified spec SHA-256: `{}`  ", inventory.spec_sha256),
        format!("Atomic event IDs: `{}`", events.len()),
        String::new(),
        "## Families".into(),
        String::new(),
        "| Spec | Rust enum | Owning crates | Producer symbols | Privacy | Default delivery | Migration task |".into(),
        "| --- | --- | --- | --- | --- | --- | --- |".into(),
    ];
    for family in &inventory.families {
        lines.push(format!(
            "| {} | `{}` | {} | {} | `{}` | `{}` | {} |",
            family.section,
            family.enum_name,
            quoted(&family.owning_crates),
            quoted(&family.producer_symbols),
            family.privacy_class,
            family.default_delivery_class,
            family.migration_task
        ));
    }
    lines.extend([
        String::new(),
        "## Stable event IDs".into(),
        String::new(),
        "| Event ID | Spec | Delivery | Privacy | Projection profile | Projected keys |".into(),
        "| --- | --- | --- | --- | --- | --- |".into(),
    ]);
    for event in events {
        let keys = event
            .projected_keys
            .iter()
            .map(|key| format!("`{key}`"))
            .collect::<Vec<_>>()
            .join(", ");
        lines.push(format!(
            "| `{}` | {} | `{}` | `{}` | `{}` | {} |",
            event.id,
            event.section,
            event.delivery_class,
            event.privacy_class,
            event.projection_profile,
            keys
        ));
    }
    lines.extend([
        String::new(),
        "## Amendment procedure".into(),
        String::new(),
        inventory.amendment_procedure.clone(),
        String::new(),
    ]);
    lines.join("\n")
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct Payload<'a> {
    schema_version: u32,
    spec_sha256: &'a str,
    reason_codes: &'a [String],
    events: &'a [Event<'a>],
}

pub(super) fn typescript<'a>(
    inventory: &'a Inventory,
    events: &'a [Event<'a>],
) -> DynResult<String> {
    let payload = Payload {
        schema_version: inventory.schema_version,
        spec_sha256: &inventory.spec_sha256,
        reason_codes: &inventory.reason_codes,
        events,
    };
    Ok(format!(
        "// Generated by scripts/generate-runtime-event-inventory.py.\nexport const runtimeEventInventory = {} as const;\n",
        serde_json::to_string_pretty(&payload)?
    ))
}
